# Generated by Django 4.2.3 on 2023-08-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('big_number', models.BigIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('slug', models.SlugField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
